language: objective-c

before_install:
    - gem install cocoapods
    - brew update
    - brew uninstall xctool && brew install xctool

script:
    - xctool -workspace MQTTExample.xcworkspace -scheme MQTTExample -sdk iphonesimulator -configuration Release build

